-- MySQL Script generated by MySQL Workbench
-- Mon Oct 17 17:43:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema farmaticos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmaticos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmaticos` DEFAULT CHARACTER SET utf8 ;
USE `farmaticos` ;

-- -----------------------------------------------------
-- Table `farmaticos`.`Farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaticos`.`farmacia` (
  `idfarmacia` INT NOT NULL,
  `nomefarmacia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfarmacia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmaticos`.`Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaticos`.`medicamento` (
  `idmedicamento` INT NOT NULL,
  `nomemedicamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmedicamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmaticos`.`Preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmaticos`.`preco` (
  `idpreco` INT NOT NULL,
  `numpreco` DATETIME NOT NULL,
  `preco` DECIMAL(9,2) NOT NULL,
  `idfarmacia` INT NOT NULL,
  `idmedicamento` INT NOT NULL,
  PRIMARY KEY (`idpreco`),
  INDEX `idpreco_idfarmacia_idx` (`idfarmacia` ASC) VISIBLE,
  INDEX `idpreco_idmedicamento_idx` (`idmedicamento` ASC) VISIBLE,
  CONSTRAINT `idpreco_idfarmacia`
    FOREIGN KEY (`idfarmacia`)
    REFERENCES `farmaticos`.`farmacia` (`idfarmacia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idpreco_idmedicamento`
    FOREIGN KEY (`idmedicamento`)
    REFERENCES `farmaticos`.`medicamento` (`idmedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;